### ISSUE TITLE
issue after update to accelerate 2.0

### ISSUE THREAD

**Issue by guzongyuan** [ContinuumIO/numbapro-examples#8]
running the examples after update to accelerate 2.0, it shows:
numbapro:1: ImportWarning: The numbapro package is deprecated in favour of the accelerate package. Please update your code to use equivalent functions from accelerate.

Is there any new example?

**Comment by gmarkall** [comment]
Thanks for reporting this - I've gone through all the examples and updated them for Numba 0.22.1 and Accelerate 2.0, currently in this PR: https://github.com/ContinuumIO/numbapro-examples/pull/9

**Comment by gmarkall** [comment]
The examples are now updated on master.
